=== srl295/icu/source/samples/XMLConverter/samples/personal.dtd
<?xml encoding="US-ASCII"?>

<!-- Revision: 24 1.2 docs/data/personal.dtd, xml4jdocs, xml4j-jtcsv, xml4j_1_1_1  -->

<!ELEMENT personnel (person)+>
<!ELEMENT person (name,email*,url*,link?)>
<!ATTLIST person id ID #REQUIRED>
<!ELEMENT family (#PCDATA)>
<!ELEMENT given (#PCDATA)>
<!ELEMENT name (#PCDATA|family|given)*>
<!ELEMENT email (#PCDATA)>
<!ELEMENT url EMPTY>
<!ATTLIST url href CDATA #REQUIRED>
<!ELEMENT link EMPTY>
<!ATTLIST link
  manager IDREF #IMPLIED
  subordinates IDREFS #IMPLIED>

=== srl295/icu/source/samples/XMLConverter/samples/a-ebc-ascii.xml
<?xml version="1.0" encoding="ascii"?>

<!-- Revision: 25 1.2 docs/data/personal.xml, xml4jdocs, xml4j-jtcsv, xml4j_1_1_3  -->

<!DOCTYPE personnel SYSTEM "personal.dtd">

<personnel>

  <person id="H.MARUYAMA" >
    <name><family>MARUYAMA</family> <given>Hiroshi</given></name>
    <email>maruyama@jp.ibm.com</email>
    <link subordinates="  N.URAMOTO    K.TAMURA "/>
  </person>

  <person id="N.URAMOTO">
    <name><family>URAMOTO</family> <given>Naohiko</given></name>
    <email>uramoto@jp.ibm.com</email>
    <link manager="		H.MARUYAMA"/>
  </person>

  <person id="K.TAMURA">
    <name>
      <family>TAMURA</family> <given>Kent</given>
    </name>
    <!-- This URL is mail address.-->
    <url href="mailto:kent@trl.ibm.co.jp"/>
    <url href="mailto:tkent@jp.ibm.com"/>
    <link manager="H.MARUYAMA"/>
  </person>

</personnel>
